### PR TITLE
Added php-macaroons to other known implementations

### PR DESCRIPTION
**Pull request by cmbankester**

### CODE REVIEW

**Comment by nitram509** [comment]
Thank you for adding the link.

**Comment by cmbankester** [comment]
Np. I guess it would be easier to add me to the macaroons-io organization. Btw, another coworker (a designer) is contemplating submitting a PR to update the styles for macaroons.io. Just a heads-up.

**Comment by tarcieri** [comment]
@cbankester nice... I've thought about helping on that front too. I have a nice pure-CSS Macaroons logo contributed by another designer

**Comment by nitram509** [comment]
Cool, would be great to have it under a Creative Commons license, too
 :+1:

**Pull request merged**
